spring:
  application:
    name: camunda-demo
  jpa:
    database: POSTGRESQL
    show-sql: true
    generate-ddl: true
    hibernate.ddl-auto: create-drop
    properties.hibernate.jdbc.lob.non_contextual_creation: true
  datasource:
      url: 'jdbc:h2:mem:testdb'
      username: SA
      password: null
      driver-class-name: org.h2.Driver
