#DataSource
spring:
  application:
    name: 'camunda-demo'
  jpa:
    database: POSTGRESQL
    show-sql: true
    generate-ddl: true
    hibernate.ddl-auto: create-drop
    properties.hibernate.jdbc.lob.non_contextual_creation: true
  datasource:
    platform: postgres
    url: 'jdbc:postgresql://ubuntu-dc:5432/camunda'
    username: postgres
    password: 1
    driver-class-name: org.postgresql.Driver
